In [1]:
import sys
import os
import argparse
import numpy as np
import pandas as pd

In [4]:
train = pd.read_csv('train_expr.txt', sep = '\t', index_col = 0)

In [5]:
train.head()

GTEX-13FTX-0326-SM-5J2NG  GTEX-WK11-0006-SM-3NB3J  \
geneid                                                                  
ENSG00000104879.4                  -0.680895                -0.529919   
ENSG00000143632.10                 -0.622342                -0.477865   
ENSG00000244734.2                   0.493421                 1.696895   
ENSG00000188536.8                   0.401353                 1.626741   
ENSG00000206172.4                   0.516500                 1.729560   

                    GTEX-13OVL-0326-SM-5IJCS  GTEX-YEC3-0826-SM-4WWFP  \
geneid                                                                  
ENSG00000104879.4                  -0.446931                -0.696486   
ENSG00000143632.10                 -0.380450                -0.615103   
ENSG00000244734.2                  -0.623790                -0.780641   
ENSG00000188536.8                  -0.587916                -0.786670   
ENSG00000206172.4                  -0.726352                -0.762383   

                    GTEX-WFG8-2326-SM-5S2UE  GTEX-SJXC-0726-SM-2XCFJ  \
geneid                                                                 
ENSG00000104879.4                 -0.596440                -0.587053   
ENSG00000143632.10                -0.650067                -0.556104   
ENSG00000244734.2                 -0.640793                -0.406726   
ENSG00000188536.8                 -0.562416                -0.369706   
ENSG00000206172.4                 -0.620865                -0.525214   

                    GTEX-RVPU-2426-SM-2XCAR  GTEX-13W46-0926-SM-5LU3T  \
geneid                                                                  
ENSG00000104879.4                  1.853997                 -0.503557   
ENSG00000143632.10                 1.985546                 -0.474911   
ENSG00000244734.2                 -0.507259                 -0.341086   
ENSG00000188536.8                 -0.468031                 -0.219668   
ENSG00000206172.4                 -0.528507                 -0.213359   

                    GTEX-13JUV-0526-SM-5K7XE  GTEX-YF7O-2526-SM-5IFJX  ...  \
geneid                                                                 ...   
ENSG00000104879.4                  -0.476697                 1.743965  ...   
ENSG00000143632.10                 -0.454111                 1.794067  ...   
ENSG00000244734.2                   0.660264                -1.167895  ...   
ENSG00000188536.8                   0.660976                -0.995400  ...   
ENSG00000206172.4                   0.603325                -0.950248  ...   

                    GTEX-ZDTS-0226-SM-5HL7Q  GTEX-Y5V5-2426-SM-5IFJA  \
geneid                                                                 
ENSG00000104879.4                 -0.782799                -0.598077   
ENSG00000143632.10                -0.784953                -0.616822   
ENSG00000244734.2                 -1.112056                 0.096588   
ENSG00000188536.8                 -1.020313                 0.121388   
ENSG00000206172.4                 -1.030625                 0.068395   

                    GTEX-13VXU-0826-SM-5KLZ2  GTEX-11LCK-1226-SM-5Q5AM  \
geneid                                                                   
ENSG00000104879.4                  -0.555558                  1.837806   
ENSG00000143632.10                 -0.605833                  1.950436   
ENSG00000244734.2                  -0.028634                 -1.340025   
ENSG00000188536.8                   0.022120                 -1.260669   
ENSG00000206172.4                  -0.072431                 -1.245723   

                    GTEX-139T4-0326-SM-5K7XN  GTEX-Y5V6-0526-SM-4VBRV  \
geneid                                                                  
ENSG00000104879.4                   1.209599                -0.470998   
ENSG00000143632.10                  0.922770                -0.602586   
ENSG00000244734.2                  -0.678157                -0.834713   
ENSG00000188536.8                  -0.59478

In [6]:
t_train = train.transpose()
t_train.shape

(1089, 100)

In [116]:
def myKmeans(data, k, centers, maxit):
    n = data.shape[0] #no of samples
    d = data.shape[1] #no of features
    clusters = np.empty(shape = n)
    itr = 0
    while(itr < maxit):
        #assign clusters
        for i in range(n):
            distances = np.empty(shape = k)
            for j in range(k):
                distances[j] = distance(centers[j,:], data[i,:])
                clusters[i] = distances.argmin()
        #recompute centers
        for j in range(k):
            whr_j = np.where(clusters == j)[0]
            centers[j,:] = np.mean(data[whr_j,:], axis=0)
        itr += 1
    return(clusters,centers)

In [80]:
np.mean(data[np.where(model[0] == 1)[0],],axis =0)

array([2., 2.])

In [101]:
np.mean(data[np.where(model[0] == 1),:],axis=0) == data[1]

array([[ True,  True,  True, ...,  True,  True,  True],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [106]:
data[np.where(model[0] == 1),] == data[np.where(model[0] == 1),:]

array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])

In [107]:
data[1]

array([-0.48796532, -0.53499354,  1.70463211,  1.71569715,  1.72222842,
       -0.51320928, -0.53543358, -0.56844345, -0.53283982, -0.5107828 ,
       -0.39528389, -0.50606087, -0.51697992, -0.42968371, -0.48437216,
       -0.64366301, -0.61088338, -0.51287674, -0.50943845, -0.8185465 ,
       -0.50885581, -1.09817645, -0.17298727, -0.5918025 , -0.53893596,
        1.56142233, -0.51449441, -0.48652019, -0.75641338, -0.54810023,
       -0.59436882, -0.65222669, -0.44599151,  1.59933313, -0.56616875,
       -0.44195259, -0.52270326,  1.4845693 , -0.53207159, -0.5924278 ,
       -1.02297888, -0.58072736, -0.78800496,  1.60012026, -0.57888996,
       -0.50258455, -1.39761591,  1.7702036 , -0.62606333,  1.738622  ,
       -0.5673883 , -0.51838931, -1.66976097, -0.91857986, -0.42658589,
        1.68263734, -0.77777853,  1.78170804,  1.66769765,  1.42590425,
       -0.63170286,  1.41210204,  1.78342574, -0.59855558,  1.71511168,
        1.38576943, -0.53155949,  1.44254878,  0.62534953, -1.58

In [8]:
cntrs = t_train.values[1:,:]
dat = t_train.values[0:100,]
k = 2
maxit = 50
mk = myKmeans(dat,k,cntrs,50)

NameError: name 'ii' is not defined

In [117]:
model = myKmeans(data,5,data[0:5],10)

In [118]:
model[0][0:9]

array([0., 1., 2., 3., 4., 3., 0., 3., 2.])

In [9]:
def avg_distance_from_centroid(model,data,k):
    distances = np.empty(shape = k)
    clusters = model[0]
    for j in range(k):
        whr_j = np.where(clusters == j)[0]
        s = 0
        temp_mat = data[whr_j,]
        for i in range(len(whr_j)):
            s += distance(model[1][j],temp_mat[i])
        distances[j] = s
    return np.mean(distances)

In [13]:
def distance(p1, p2):
    return np.linalg.norm(p1  -  p2)

In [64]:
kmin = 2
kmax = 10
tries = kmax - kmin + 1
rng = range(kmin, kmax + 1)
mean_distances = np.empty(shape = tries)
try_no = 0
data = t_train.values
for i in rng:
    model = myKmeans(data,i,data[0:i],10)
    mean_distances[try_no] = avg_distance_from_centroid(model,data,i) 
    try_no += 1

In [67]:
model[0][0:10]

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [113]:
#Bic Criteria
k = 5
sigma = np.empty(shape = k)
for i in range(k):
    distances = 0
    wch_k = np.where(model[0] == i)[0]
    for j in range(len(wch_k)):
        distances += distance(model[1][i],data[wch_k[j],:])
    sigma[i] = distances/len(wch_k)

In [145]:
data.shape

(1089, 100)

In [132]:
innr = np.empty(shape = k)
for i in range(k):
    distances = 0
    wch_k = np.where(model[0] == i)
    inr = 0
    for j in range(len(wch_k)):
        inr += 1/np.sqrt(2*np.pi*sigma[i])*np.exp(-1/2/(sigma[i]**2)*distance(model[1][i],data[wch_k[j],:]))
    innr[i] = inr

In [133]:
innr

array([0.01183318, 0.01199737, 0.01820021, 0.01688628, 0.01305942])

In [127]:
prod = 1
for i in range(len(innr)):
    prod *= innr[i]

In [151]:
bic = np.empty(shape = len(rng))
for m in rng:
    k = m
    model = myKmeans(data,k,data[0:k],10)
    sigma = np.empty(shape = k)
    for i in range(k):
        distances = 0
        wch_k = np.where(model[0] == i)[0]
        for j in range(len(wch_k)):
            distances += distance(model[1][i],data[wch_k[j],:])
        sigma[i] = distances/len(wch_k)
    innr = np.empty(shape = k)
    for i in range(k):
        distances = 0
        wch_k = np.where(model[0] == i)
        inr = 0
        for j in range(len(wch_k)):
            inr += 1/np.sqrt(2*np.pi*sigma[i])*np.exp(-1/2/(sigma[i]**2)*distance(model[1][i],data[wch_k[j],:]))
        innr[i] = inr
    prod = 1
    for i in range(k):
        prod *= innr[i]
    bc = -2*np.log(prod) + (k*101)*np.log(1089)
    bic[m-2] = bc

In [160]:
inr = 0
n = 0
bic = np.empty(shape = (9,1089))
for m in rng:
    k = m
    model = myKmeans(data,k,data[0:k],10)
    sigma = np.empty(shape = k)
    for i in range(k):
        distances = 0
        wch_k = np.where(model[0] == i)[0]
        for j in range(len(wch_k)):
            distances += distance(model[1][i],data[wch_k[j],:])
        sigma[i] = distances/len(wch_k)
    lninr = np.empty(shape = data.shape[0])
    for n in range(data.shape[0]):
        for j in range(k):
            inr += 1/np.sqrt(2*np.pi*sigma[j])*np.exp(-1/2/(sigma[j]**2)*distance(model[1][j],data[i,:]))
        lninr[n] = np.log(inr)
    bic[m-2] = lninr

In [166]:
np.mean(bic,axis=1)

array([4.53209426, 6.16547862, 6.9194296 , 7.42644315, 7.85110929,
       8.15945905, 8.42543252, 8.67573519, 8.86612957])

In [158]:
bic.shape

AttributeError: 'list' object has no attribute 'shape'

In [154]:
data.shape[0]

1089

In [114]:
#Using elbow method and detecting elbow at less than 25% change
chk = 0
i_for_k = 0
for i in range(len(mean_distances) - 1):
    if chk != 1:
        if ((mean_distances[i] - mean_distances[i+1])/mean_distances[i]) < 0.25:
            i_for_k = i
            chk = 1
if chk == 0:
    i_for_k = len(mean_distances) - 1
optimal_k = rng[i_for_k] 
optimal_k

5

In [112]:
301/932

0.3229613733905579

In [120]:
def predict(model, test_data):
    k = len(model[1])
    n = test_data.shape[0]
    centers = model[1]
    clusters = np.empty(shape = n)
    for i in range(n):
            distances = np.empty(shape = k)
            for j in range(k):
                distances[j] = distance(centers[j,:], test_data[i,:])
            clusters[i] = distances.argmin()
    return clusters

In [132]:
test = pd.read_csv('test_expr.txt', sep = '\t', index_col = 0)
test = test.transpose()
test_v = test.values
train_t = t_train.values
model_optimal = myKmeans(train_t, optimal_k, train_t[0:optimal_k,],10)

In [128]:
y_pred = predict(model_optimal,test_v)

In [134]:
test.index

Index(['GTEX-ZYW4-1526-SM-5SIBA', 'GTEX-WVJS-0226-SM-4MVOU',
       'GTEX-WY7C-0226-SM-3NB37', 'GTEX-RVPU-0005-SM-2TF6L',
       'GTEX-145ME-1926-SM-5SI9S', 'GTEX-SNOS-0006-SM-32PLH',
       'GTEX-QEG5-0006-SM-2I5FZ', 'GTEX-Z9EW-1826-SM-5CVMA',
       'GTEX-W5WG-2526-SM-4SOJ2', 'GTEX-11XUK-2126-SM-5EQLR',
       ...
       'GTEX-11EMC-0226-SM-5EGLP', 'GTEX-W5WG-1426-SM-4KKZP',
       'GTEX-SNOS-0226-SM-32PLR', 'GTEX-RTLS-0626-SM-5SI7Z',
       'GTEX-11ZVC-2626-SM-5FQTA', 'GTEX-11OC5-0326-SM-5PNW5',
       'GTEX-S4UY-0226-SM-3K2AP', 'GTEX-1399T-2426-SM-5L3FJ',
       'GTEX-ZLWG-2226-SM-5DUWO', 'GTEX-1477Z-0005-SM-5PNWD'],
      dtype='object', length=727)

In [143]:
f = open('testwrite.txt','w')
for i in range(len(y_pred)):
    line = str(test.index[i]) + '\t' + str(y_pred[i]) + '\n'
    f.write(line)
f.close()

In [146]:
a = '5'
int(a)

5

In [63]:
values = np.array([1,2,3,1,2,4,5,6,3,2,1])
searchval = 3
ii = np.where(values == searchval)[0]
#np.mean(t_train.as_matrix()[ii,:], axis = 0)

In [19]:
r1 = t_train.iloc[0]
r2 = t_train.iloc[1]
np.linalg.norm(r1 - r2)
#np.sqrt(np.sum((r1 - r2)**2))

10.997409469503662